export const timezones = [
  // North America (west to east)
  "America/Honolulu",      // Hawaii (UTC-10, no DST)
  "America/Anchorage",     // Alaska (UTC-9)
  "America/Los_Angeles",   // US Pacific Time (UTC-8)
  "America/Denver",        // US Mountain Time (UTC-7)
  "America/Chicago",       // US Central Time (UTC-6)
  "America/New_York",      // US Eastern Time (UTC-5)
  "America/Mexico_City",   // Mexico Central Time (UTC-6)
  "America/Guatemala",     // Guatemala (UTC-6)
  "America/Tegucigalpa",   // Honduras (UTC-6)
  "America/El_Salvador",   // El Salvador (UTC-6)

  // Latin America (west to east, roughly south to north)
  "America/Santiago",      // Chile (UTC-4/UTC-3 with DST)
  "America/La_Paz",        // Bolivia (UTC-4)
  "America/Manaus",        // Brazil Amazon (UTC-4)
  "America/Argentina/Buenos_Aires", // Argentina (UTC-3)
  "America/Montevideo",    // Uruguay (UTC-3)
  "America/Sao_Paulo",     // Brazil Southeast (UTC-3)
  "America/Asuncion",      // Paraguay (UTC-4/UTC-3 with DST)
  "America/Lima",          // Peru (UTC-5)
  "America/Bogota",        // Colombia (UTC-5)
  "America/Caracas",       // Venezuela (UTC-4)
  "America/Port_of_Spain", // Trinidad and Tobago (UTC-4)
  "America/Santo_Domingo", // Dominican Republic (UTC-4)
  "America/Havana",        // Cuba (UTC-5/UTC-4 with DST)

  // Europe (west to east)
  "Europe/London",         // Western European Time / GMT (UTC+0)
  "Europe/Paris",          // Central European Time (UTC+1)
  "Europe/Moscow",         // Moscow Time (UTC+3)

  // Africa (west to east, roughly south to north)
  "Africa/Casablanca",     // Morocco (UTC+1)
  "Africa/Accra",          // Ghana (UTC+0)
  "Africa/Luanda",         // Angola (UTC+1)
  "Africa/Lagos",          // Nigeria (UTC+1)
  "Africa/Kinshasa",       // DR Congo western (UTC+1)
  "Africa/Johannesburg",   // South Africa (UTC+2)
  "Africa/Maputo",         // Mozambique (UTC+2)
  "Africa/Algiers",        // Algeria (UTC+1)
  "Africa/Cairo",          // Egypt (UTC+2)
  "Africa/Nairobi",        // Kenya (UTC+3)
  "Africa/Dar_es_Salaam",  // Tanzania (UTC+3)
  "Africa/Kampala",        // Uganda (UTC+3)
  "Africa/Addis_Ababa",    // Ethiopia (UTC+3)

  // Middle East (west to east)
  "Asia/Riyadh",           // Saudi Arabia (UTC+3)
  "Asia/Baghdad",          // Iraq (UTC+3)
  "Asia/Tehran",           // Iran (UTC+3:30)

  // South Asia (west to east)
  "Asia/Karachi",          // Pakistan (UTC+5)
  "Asia/Kolkata",          // India (UTC+5:30)
  "Asia/Colombo",          // Sri Lanka (UTC+5:30)
  "Asia/Dhaka",            // Bangladesh (UTC+6)
  "Asia/Kathmandu",        // Nepal (UTC+5:45)

  // Southeast Asia (west to east)
  "Asia/Yangon",           // Myanmar (UTC+6:30)
  "Asia/Bangkok",          // Thailand (UTC+7)
  "Asia/Ho_Chi_Minh",      // Vietnam (UTC+7)
  "Asia/Phnom_Penh",       // Cambodia (UTC+7)
  "Asia/Vientiane",        // Laos (UTC+7)
  "Asia/Jakarta",          // Indonesia western (UTC+7)
  "Asia/Kuala_Lumpur",     // Malaysia peninsular (UTC+8)
  "Asia/Makassar",         // Indonesia central (UTC+8)
  "Asia/Manila",           // Philippines (UTC+8)
  "Asia/Jayapura",         // Indonesia eastern (UTC+9)

  // East Asia and Central Asia (west to east)
  "Asia/Dushanbe",         // Tajikistan (UTC+5)
  "Asia/Tashkent",         // Uzbekistan (UTC+5)
  "Asia/Shanghai",         // China Standard Time (UTC+8)
  "Asia/Tokyo",            // Japan (UTC+9)

  // Oceania (west to east)
  "Australia/Sydney",      // Australian Eastern Time (UTC+10/UTC+11 with DST)
  "Pacific/Port_Moresby",  // Papua New Guinea (UTC+10)
  "Pacific/Auckland",      // New Zealand (UTC+12/UTC+13 with DST)

  // Global Reference
  "Etc/UTC"                // Coordinated Universal Time (UTC+0)
];
